mobileappdevhm/dev-team-1-cie-app-in-flutter

- lib/model/login/loginData.dart
- lib/utils/routes.dart
- lib/views/login.dart
- lib/views/start.dart
> added login page

- .gitignore
.gitignore change, nothing too significant
> Ignore IOS device specific files to avoid merge conflicts

- lib/views/maps.dart
> Changes to maps.dart

- lib/utils/cieStyle.dart
- lib/utils/staticVariables.dart
- lib/views/maps.dart
Aesthetic Improvements to Maps Page & internal refactoring to code
> Aesthetic Improvements to Maps Page & internal refactoring to code

- .gitignore
- lib/utils/cieColor.dart
- lib/utils/cieStyle.dart
- lib/views/login.dart
- lib/views/tabs.dart
- lib/widgets/courseDetails.dart
- lib/widgets/courseListItem.dart
Added CiEColor Class and changed Color from RGBO to CiEColor.
> CiEColor class

- .travis.yml
- README.md
> Coveralls.io implementation

- test/views/maps_test.dart
Wrote some Unit tests.
widget tests are now working.
> Tests for Map

- lib/model/course/course.dart
- lib/model/course/courses_mock.dart
- lib/widgets/courseList.dart
- lib/widgets/courseListItem.dart
- test/model/course/course_test.dart
- test/model/course/courses_mock_test.dart
- test/presenter/courseListPresenter_test.dart
- test/widgets/courseList_test.dart
- Implemented a dropdown to filter courses by department
- Implemented search functionality to search for courses by typing when activated. Will file an issue to use a real search algorithm like the Boyer–Moore algorithm or something.
- Refactored some of our mocks so more courses could be added.
- Also made some of the tests less hard-coded so we could change our mocks without too much of a headache.
- Otherwise nothing too crazy!
> Major dropdown and search feature

- lib/utils/staticVariables.dart
- lib/widgets/courseList.dart
- test/widgets/courseList_test.dart
- Added a few more tests to minimize my damage for code coverage from the latest pull request :P
> Adding more tests regarding course lists and favorites page

- lib/views/tabs.dart
Fixed tabs swipe bug (https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/issues/43)
> fixed tabs swipe bug

- lib/views/maps.dart
Simple review. Fixes this error.
> fix compile error

- lib/utils/cieStyle.dart
- lib/utils/staticVariables.dart
- lib/views/login.dart
- lib/views/settings.dart
- lib/views/start.dart
- lib/views/takenCourses.dart
- lib/widgets/prevCourseList.dart
- lib/widgets/prevCourseListItem.dart
- test/views/settings_test.dart
- addedTaken Courses as a separate screen
- replaced button color with CieColor
- added some static variables to the settings page
- changed some tests due to the static variables and text changes
> Taken Courses as a separate screen

- lib/generic/genericAlert.dart
- lib/utils/staticVariables.dart
- lib/widgets/courseList.dart
- Simple alert functionality after clicking the submission button on the favorites page
- Wrote with Futures so it'll be easy to submit a POST request to Nine later on
- No tests included here, TODO for next Sprint
https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/issues/94
> Add alert functionality to course submission button on favorites page

- lib/views/login.dart
- changed Text to FlatButton
- added _launchUrl method
- added corresponding urls
Issue: #88
> Made links on login.dart working

- lib/views/maps.dart
- test/views/maps_test.dart
- added place_id of campuses
- used google maps api v1
- changed open maps link
- added testcases
Issue: #66
> fixed open map problem on android

- test/views/tab_test.dart
- merged if's
- more improvements have to be done
> improved testing

- lib/utils/schedulingUtility.dart
- lib/utils/staticVariables.dart
- lib/views/schedule.dart
- test/utils/schedulingUtility_test.dart
I thought Karlstrasse was the building 2 minutes away from Lothstrasse in the initial implementation for time conflict checks haha.
Fixed in this commit and included a little bit of refactoring.
> Fix time conflict detection and made more modular

- test/model/course/course_test.dart
Added massive tests for the builder class
> Add builder tests

- lib/generic/genericIcon.dart
- lib/model/course/course.dart
- lib/presenter/courseListPresenter.dart
- lib/utils/cieStyle.dart
- lib/utils/staticVariables.dart
- lib/widgets/courseDetails.dart
- lib/widgets/courseListItem.dart
- lib/widgets/prevCourseListItem.dart
- test/widgets/courseDetails_test.dart
#142 #44 
Course Details view is now more responsive and text overflow is handled.
> F description heart clickable

- lib/utils/staticVariables.dart
- lib/views/settings.dart
- lib/widgets/courseListItem.dart
- lib/widgets/timeTableItem.dart
#111 
I changed the views to support smaler devices.
Overview of changes:
- Settings Page Scrollable
- Removed "Time" from Course List this is obvious
- In Course list title will end with ... after third row
- In Timetable title will end with ... after second row
- In Timetable moved professor to other position
- In Timetable pofessor name can only be 1 line it will end with ... when there is overflow
> B text overflow andi

- lib/main.dart
> No device rotation

- .gitignore
- lib/views/login.dart
#150 
View should no fit smaller screens (tested on 3,7") and larger ones. It does not look perfect on large screens, but I couldn't get a change on screen height to work.
Tried:  MediaQuery.of(context).size.height (but it seems, that this value is not set correctly or maybe to late)
> B padding on login page

- lib/widgets/courseList.dart
https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/issues/145
If you don't like the color or look in any way, feel free to make a suggestion on this pull request for review.
> Match update pull down color with the blue used elsewhere in the application

- lib/utils/cieColor.dart
- lib/utils/cieStyle.dart
- lib/views/tabs.dart
Discuss if you guys like this better (or if you have other ideas for theme improvements).
Issue for discussion here:
https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/issues/138
> Pull request for theme discussion

- lib/utils/staticVariables.dart
- lib/views/tabs.dart
- lib/widgets/courseList.dart
- test/widgets/courseList_test.dart
Guests cant push courses to nine lottery
> Guests cant push courses to nin lottery

- .travis.yml
Implemented the possibility to build IPAs -> iOS App - Files on Travis.
Now we can check if building on iOS is also working.
> Feature build iOS apps on Travis

- lib/model/course/course.dart
- lib/model/course/courses_mock.dart
- lib/model/course/details/correlation.dart
- lib/model/course/details/date.dart
- lib/model/course/details/lecturer.dart
- lib/model/course/details/room.dart
- lib/presenter/courseListPresenter.dart
- test/model/course/course_test.dart
- test/model/user/user_test.dart
New object structure:
- dates of course
- rooms
- lecturers
- correlations
Changed tests:
- use setup
- use new structure
Issue: #185
> Feature: use object structure from nine

- lib/presenter/courseListPresenter.dart
- lib/utils/cieStyle.dart
- lib/utils/staticVariables.dart
- lib/widgets/courseDetails.dart
- test/widgets/courseDetails_test.dart
There is now a reason displayed why there are time conflicts
> Reasons why there is a conflict are now displayed

- .travis.yml
- lib/presenter/courseListPresenter.dart
- lib/widgets/courseDetails.dart
- lib/widgets/courseList.dart
- test/presenter/courseListPresenter_test.dart
> Bug: reimplement favorite saving

- lib/presenter/courseListPresenter.dart
- lib/widgets/courseDetails.dart
> Readd Feature to show the reason why there is a time conflict.

- lib/main.dart
- lib/model/course/course.dart
- lib/presenter/courseListPresenter.dart
- lib/utils/staticVariables.dart
- lib/views/schedule.dart
- lib/views/tabs.dart
- lib/views/takenCourses.dart
- lib/widgets/courseList.dart
- test/views/tab_test.dart
Spelling changes, padding, and stuff like this
> last minute aesthetic improvements throughout the app

- lib/views/schedule.dart
- lib/views/tabs.dart
> fix momentary crash, making timetable widget stateless

- lib/utils/staticVariables.dart
- lib/views/schedule.dart
- lib/views/tabs.dart
- lib/widgets/courseDetails.dart
> F show campus in course details

- test/utils/nineAPIConsumer_test.dart
one test here to see if it builds on travis
> add nineAPIConsumer internet test

- lib/presenter/courseListPresenter.dart
- lib/utils/staticVariables.dart
- lib/views/schedule.dart
- lib/views/tabs.dart
- lib/widgets/courseDetails.dart
- test/model/course/course_test.dart
- test/model/user/user_test.dart
- test/widgets/timeTableItem_test.dart
Implemented contact professor. If email is not available or is mock email user will be informed that he cant contact professor.
> F open email to prof

- lib/main.dart
- lib/utils/analytics.dart
- lib/views/login.dart
- lib/views/maps.dart
- lib/views/schedule.dart
- lib/views/settings.dart
- lib/views/start.dart
- lib/views/tabs.dart
- lib/widgets/courseList.dart
- lib/widgets/courseListItem.dart
- lib/widgets/privacyPage.dart
Firebase analytics can now be turned off/on by the user metrics button on the profile page
> Usermetrics

- lib/model/user/user.dart
> Bugfix: easiest fix for #217

- README.md
added project homepage to readme
> Update Readme to include project homepage

- lib/views/login.dart
If wrong user data is submitted to nine there will be an confirm dialog displayed.
Issue: #218
> Bugfix: Unvalid Credentials after sending wrong user data

- lib/views/login.dart
- lib/views/settings.dart
- lib/views/start.dart
After a click on start a previous logged in user will be redirected to the schedule.
> Feature: keep user logged in

- lib/generic/genericIcon.dart
Changed color of blue to red :-) Awesome! 👍
> Feature: changed color of login spinner

- lib/presenter/courseListPresenter.dart
Remove remaining Mock data from Prod.
> Remove remaining Mock data from Prod.

- lib/model/course/course.dart
- lib/presenter/courseListPresenter.dart
- lib/presenter/currentUserPresenter.dart
- lib/utils/cieStyle.dart
- lib/widgets/courseDetails.dart
- lib/widgets/courseList.dart
- lib/widgets/courseListItem.dart
- lib/widgets/prevCourseListItem.dart
- lib/widgets/timeTableItem.dart
- test/model/course/course_test.dart
- test/model/course/courses_mock_test.dart
- test/presenter/courseListPresenter_test.dart
- test/presenter/currentUserPresenter_test.dart
Issues: #236 + #237 
- There are now courses in every department (at least in those which have courses on nine).
- Course info fits screen
- Course list has selected the user department by default.
- Course list has default department '13' if user have not specified a department on nine.
> Bugfix: show courses in all departments + small screens

- android/app/build.gradle
- android/app/google-services.json
> added data for release of version 2 (1.1)

- lib/widgets/courseList.dart
> Add filter all departments function + Some refactoring

- lib/widgets/courseList.dart
Easy code review 👍 
https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/issues/252
Just compares both the typed search text and course name using lower case logic so search isn't forced to be case sensitive.
> use lower case logic in courseList to avoid case sensitive search

- lib/generic/genericAlert.dart
- lib/generic/genericIcon.dart
- lib/generic/genericShowInstruction.dart
- lib/presenter/courseListPresenter.dart
- lib/utils/cieStyle.dart
- lib/utils/staticVariables.dart
- lib/views/login.dart
- lib/views/settings.dart
- lib/widgets/courseList.dart
- test/generic/genericIcon_test.dart
- test/generic/genericShowInstruction_test.dart
- test/main_test.dart
- test/model/course/course_test.dart
- test/model/course/details/room_test.dart
- test/presenter/courseListPresenter_test.dart
- test/presenter/currentUserPresenter_test.dart
- test/utils/routes_test.dart
- test/views/settings_test.dart
- test/widgets/privacyPage_test.dart
- removed some unneeded methods
- formatted code
- removed unneeded imports
- removed unneeded empty lines
- added some small tests
> Code Clean up

- lib/widgets/privacyPage.dart
> Changed padding on privacy page #249

- lib/utils/staticVariables.dart
Issue: #261 fixed
also restructured other textes.
> fix issue #261

- lib/model/user/currentUser_prod.dart
- lib/utils/nineAPIConsumer.dart
- lib/views/login.dart
- lib/widgets/courseList.dart
Reroute to login page if user is not logged in
Push favorited course data to Nine API. 200 response.
> Push to nine

- lib/widgets/timeTableItem.dart
- test/widgets/timeTableItem_test.dart
Choosing to remove the day entry since the day of week is already specified in the accordion
Before
After
> remove duplicate day entry in timetable since it is already specified

- res/values/courses.json
Added old course data from nine as json file
> add courses as json mock file

- android/app/google-services.json
- ios/GoogleService-Info.plist
- lib/utils/analytics.dart
Changed the google files so new data will be pushed in the project from mr. socher instead of my private one
> Change firebase project

- lib/generic/genericShowInstruction.dart
- lib/model/course/details/lecturer.dart
- lib/model/user/currentUser_prod.dart
- lib/utils/cieStyle.dart
- lib/utils/dataManager.dart
- lib/utils/staticVariables.dart
- lib/views/addTakenCourses.dart
- lib/views/settings.dart
- lib/views/tabs.dart
- lib/views/takenCourses.dart
- lib/widgets/courseList.dart
- lib/widgets/prevCourseList.dart
- lib/widgets/prevCourseListItem.dart
- test/views/settings_test.dart
- progressbar fixed
- load data if first visit in add taken courses is before data was loaded
- refresh data through help page
> C profile page

- .travis.yml
- lib/model/course/course.dart
- lib/presenter/courseListPresenter.dart
- lib/utils/cieStyle.dart
- lib/views/settings.dart
- lib/views/takenCourses.dart
- lib/widgets/courseDetails.dart
- lib/widgets/courseListItem.dart
- lib/widgets/timeTableItem.dart
> F blocked courses

- lib/model/course/details/lecturer.dart
- lib/presenter/courseListPresenter.dart
- lib/utils/staticVariables.dart
- lib/widgets/courseDetails.dart
try to open lecturers mail, if not possible ask if profile should be opend
- profile is profile or search string on hm-website
> Lecturers email / profile

- lib/model/course/course.dart
- remove office specific html tags (<o:?></o:?) from course description
- remove empty tags, or empty whitespace tags such as <p></p> etc from course description
see #298
> Bugfix: Coursedescription HTML-Parsing

- cie_app.iml
- lib/model/user/user.dart
- lib/views/login.dart
- lib/widgets/courseList.dart
- pubspec.yaml
> Bugfix: display level error

- privacy.md
- pubspec.yaml
added privacy
removed dependency overrides
> Added privacy to link from play console
